// <auto-generated />
namespace PetSit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OwnerIdChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OwnerIdChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202409152048411_OwnerId-Changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
